# Generated by Django 3.2.5 on 2021-08-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='top_sizes',
            field=models.CharField(blank=True, choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], max_length=3, null=True),
        ),
    ]
