# Generated by Django 3.2.5 on 2021-08-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_top_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='billing_address',
        ),
    ]
