# Generated by Django 3.2.5 on 2021-08-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_billingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='user',
            new_name='belongs_to',
        ),
    ]
