# Generated by Django 3.2.5 on 2021-08-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_user_billingaddress_belongs_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='belongs_to',
            new_name='user',
        ),
    ]
