# Generated by Django 3.2.5 on 2021-08-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_belongs_to_billingaddress_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='Billaddress',
        ),
    ]
