# Generated by Django 3.2.6 on 2021-08-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210826_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferProduct',
        ),
    ]
